version: "3.8"

services:
  postgres:
    restart: unless-stopped
    image: postgres:14
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'

  redis:
    restart: unless-stopped
    image: redis
    ports:
      - '6379:6379'

volumes:
  postgres-data:
