version: "3.8"

services:
  application:
    restart: unless-stopped
    image: alexbidenko1998/admire-avatar:latest
    container_name: admire-avatar
    pull_policy: always
    volumes:
      - "files:/app/files"
    environment:
      MODE: production
    depends_on:
      - postgres
      - redis
    networks:
      - app
      - server

  postgres:
    restart: unless-stopped
    image: postgres:14
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    networks:
      - app

  redis:
    restart: unless-stopped
    image: redis
    expose:
      - 6379
    networks:
      - app

volumes:
  postgres-data:
  files:

networks:
  app:
  server:
    external: true
